name: emote-website
services:
  tor-init:
    extends:
      service: tor-init
      file: ./onion-website/docker-compose.yml
  tor:
    extends:
      service: tor
      file: ./onion-website/docker-compose.yml
  vanguards:
    extends:
      service: vanguards
      file: ./onion-website/docker-compose.yml
  nginx:
    extends:
      service: nginx
      file: ./onion-website/docker-compose.yml
  nginx-debug:
    extends:
      service: nginx-debug
      file: ./onion-website/docker-compose.yml
  express:
    extends:
      service: express
      file: ./onion-website/docker-compose.yml
    build:
      context: .
      dockerfile: ./onion-website/src/express/Dockerfile
  express-debug:
    extends:
      service: express-debug
      file: ./onion-website/docker-compose.yml
  mongo:
    extends:
      service: mongo
      file: ./onion-website/docker-compose.yml
  mongo-debug:
    extends:
      service: mongo-debug
      file: ./onion-website/docker-compose.yml
secrets:
  express:
    file: ./secrets/
  mongo-config:
    file: ./onion-website/src/mongo/secrets/.env
  mongo-root-username:
    file: ./onion-website/src/mongo/secrets/root/username.txt
  mongo-root-password:
    file: ./onion-website/src/mongo/secrets/root/password.txt
  mongo-username:
    file: ./onion-website/src/mongo/secrets/express/username.txt
  mongo-password:
    file: ./onion-website/src/mongo/secrets/express/password.txt
  mongo-dev-username:
    file: ./onion-website/src/mongo/secrets/dev/username.txt
  mongo-dev-password:
    file: ./onion-website/src/mongo/secrets/dev/password.txt
volumes:
  tor-data:
  mongo-db:
  mongo-configdb:
networks:
  tor:
    ipam:
      config:
        # Aligns with onion-website
        - subnet: 10.5.3.0/24 # 10.5.3.*
          gateway: 10.5.3.1
  nginx:
    ipam:
      config:
        # Aligns with onion-website
        - subnet: 10.5.0.0/24 # 10.5.0.*
          gateway: 10.5.0.1
  express:
    ipam:
      config:
        # Aligns with onion-website
        - subnet: 10.5.2.0/24 # 10.5.2.*
          gateway: 10.5.2.1
  mongo:
    ipam:
      config:
        # Aligns with onion-website
        - subnet: 10.5.1.0/24 # 10.5.1.*
          gateway: 10.5.1.1
