name: emote-website
services:
  tor:
    extends:
      service: tor
      file: ./onion-website/docker-compose.yml
  nginx:
    extends:
      service: nginx
      file: ./onion-website/docker-compose.yml
  nginx-debug:
    extends:
      service: nginx-debug
      file: ./onion-website/docker-compose.yml
  express:
    extends:
      service: express
      file: ./onion-website/docker-compose.yml
    build:
      context: .
      dockerfile: ./onion-website/src/express/Dockerfile
      args:
        - BUILDER_ENTRYPOINT=./onion-website/src/express/webpack/index.ts
  express-debug:
    extends:
      service: express-debug
      file: ./onion-website/docker-compose.yml
  mongo-init:
    extends:
      service: mongo-init
      file: ./onion-website/docker-compose.yml
  mongo-1:
    extends:
      service: mongo-1
      file: ./onion-website/docker-compose.yml
  mongo-2:
    extends:
      service: mongo-2
      file: ./onion-website/docker-compose.yml
  mongo-3:
    extends:
      service: mongo-3
      file: ./onion-website/docker-compose.yml
  mongo-debug:
    extends:
      service: mongo-debug
      file: ./onion-website/docker-compose.yml
  onionprobe:
    extends:
      file: ./onion-website/docker-compose.yml
      service: onionprobe
  prometheus:
    extends:
      file: ./onion-website/docker-compose.yml
      service: prometheus
  grafana:
    extends:
      file: ./onion-website/docker-compose.yml
      service: grafana
secrets:
  tor-hostname:
    file: ./onion-website/src/tor/secrets/hostname
  express:
    file: ./secrets/
  mongo-config:
    file: ./onion-website/src/mongo/secrets/.env
  mongo-keyfile:
    file: ./onion-website/src/mongo/secrets/keyFile.pem
  mongo-root-username:
    file: ./onion-website/src/mongo/secrets/root/username.txt
  mongo-root-password:
    file: ./onion-website/src/mongo/secrets/root/password.txt
  mongo-username:
    file: ./onion-website/src/mongo/secrets/express/username.txt
  mongo-password:
    file: ./onion-website/src/mongo/secrets/express/password.txt
  mongo-dev-username:
    file: ./onion-website/src/mongo/secrets/dev/username.txt
  mongo-dev-password:
    file: ./onion-website/src/mongo/secrets/dev/password.txt
  grafana-admin-username:
    file: ./onion-website/src/grafana/secrets/username.txt
  grafana-admin-password:
    file: ./onion-website/src/grafana/secrets/password.txt
  grafana-admin-email:
    file: ./onion-website/src/grafana/secrets/email.txt
configs:
  mongo-replicas:
    file: ./onion-website/src/mongo/replicas.json
volumes:
  mongo-configdb-init:
  mongo-configdb-1:
  mongo-configdb-2:
  mongo-configdb-3:
  mongo-db-init:
  mongo-db-1:
  mongo-db-2:
  mongo-db-3:
  prometheus:
  grafana-storage:
networks:
  tor:
    ipam:
      config:
        # Aligns with onion-website
        - subnet: 10.5.3.0/24 # 10.5.3.*
          gateway: 10.5.3.1
  nginx:
    ipam:
      config:
        # Aligns with onion-website
        - subnet: 10.5.0.0/24 # 10.5.0.*
          gateway: 10.5.0.1
  express:
    ipam:
      config:
        # Aligns with onion-website
        - subnet: 10.5.2.0/24 # 10.5.2.*
          gateway: 10.5.2.1
  mongo:
    ipam:
      config:
        # Aligns with onion-website
        - subnet: 10.5.1.0/24 # 10.5.1.*
          gateway: 10.5.1.1
  metrics:
    ipam:
      config:
        # Aligns with onion-website # 10.5.4.*
        - subnet: 10.5.4.0/24
          gateway: 10.5.4.1
