name: CI

on:
  push:

env:
  DOCKER_COMPOSE_VERSION: v5.3.1

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2
        with:
          version: ${{ env.DOCKER_COMPOSE_VERSION }}
      - name: Build Compose stack
        run: docker compose --profile production --profile development build
  tsc:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node modules
        run: npm ci
      - name: Run tsc
        run: npm run tsc
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node modules
        run: npm ci
      - name: Run tests
        run: npm test
